### Questions
* What is an ORM? 
    * Object Relational Mapping
    * Taking an object and making it more robust
        * sqllite connection
* lots of moving parts, creating an engine, etc.
* wtf is an engine???????
* lambda functions...sure we can use this

### Objectives
YWBAT 
* build an orm for the northwind database
* explain why orms are useful

### Outline
* Questions
* Breakdown the structure of our ORM
* Build the Parent Class
* Building Child Classes
    * Assigning functions/attributes to parent and child

In [9]:
import pandas as pd
import numpy as np
import sqlite3

import matplotlib.pyplot as plt

### Build Northwind Class - Parent

In [180]:
class Northwind():
    """
    Northwind DB Object (sqlite object)
    Attributes
    - connection
    - cursor
    
    Methods
    - list_tables
    - list_relationships
    """
    
    def __init__(self, filename=None):
        self.conn = sqlite3.connect(filename)
        self.cursor = self.conn.cursor()
        
    
    def list_table_names(self):
        query = "select name from sqlite_master where type='table';"
        result = self.cursor.execute(query).fetchall()
        tables = []
        for res in result:
            tables.append(res[0])
        return tables
    
    
    
    def has_table_name(self):
        return 'table_name' in vars(self).keys()
    
    
    
    def get_column_list(self):
        columns = None
        if self.has_table_name():
            self.cursor.execute("select * from {} limit 1;".format(self.table_name)).fetchall()
            columns = []
            desc = self.cursor.description
            for d in desc:
                columns.append(d[0])
        return columns
    
    
    def select_all(self, table_name=None):
        res = None
        if self.has_table_name():
            
            if table_name is None: 
                query = 'select * from {}'.format(self.table_name)
                res = self.cursor.execute(query).fetchall()
                return res
            
            else:
                query = 'select * from {}'.format(table_name)
                res = self.cursor.execute(query).fetchall()
                return res
            
    
    def load_table_to_pandas(self, table_name=None):
        if not self.has_table_name():
            return None
        
        
        df = pd.read_sql("select * from {}".format(self.table_name), self.conn)
        return df

### Build Employee Class - Child

In [181]:
class Employee(Northwind):
    
    def __init__(self):
        super().__init__(filename="Northwind_small.sqlite")  
        self.table_name = 'Employee'

In [182]:
em = Employee()

In [183]:
em.load_table_to_pandas()

,Id,LastName,FirstName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,City,Region,PostalCode,Country,HomePhone,Extension,Photo,Notes,ReportsTo,PhotoPath
0,1,Davolio,Nancy,Sales Representative,Ms.,1980-12-08,2024-05-01,507 - 20th Ave. E. Apt. 2A,Seattle,North America,98122,USA,(206) 555-9857,5467,None,Education includes a BA in psychology from Col...,2.0,http://accweb/emmployees/davolio.bmp
1,2,Fuller,Andrew,"Vice President, Sales",Dr.,1984-02-19,2024-08-14,908 W. Capital Way,Tacoma,North America,98401,USA,(206) 555-9482,3457,None,Andrew received his BTS commercial in 1974 and...,NaN,http://accweb/emmployees/fuller.bmp
2,3,Leverling,Janet,Sales Representative,Ms.,1995-08-30,2024-04-01,722 Moss Bay Blvd.,Kirkland,North America,98033,USA,(206) 555-3412,3355,None,Janet has a BS degree in chemistry from Boston...,2.0,http://accweb/emmployees/leverling.bmp
3,4,Peacock,Margaret,Sales Representative,Mrs.,1969-09-19,2025-05-03,4110 Old Redmond Rd.,Redmond,North America,98052,USA,(206) 555-8122,5176,None,Margaret holds a BA in English literature from...,2.0,http://accweb/emmployees/peacock.bmp
4,5,Buchanan,Steven,Sales Manager,Mr.,1987-03-04,2025-10-17,14 Garrett Hill,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,None,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp
5,6,Suyama,Michael,Sales Representative,Mr.,1995-07-02,2025-10-17,Coventry House Miner Rd.,London,British Isles,EC2 7JR,UK,(71) 555-7773,428,None,Michael is a graduate of Sussex University (MA...,5.0,http://accweb/emmployees/davolio.bmp
6,7,King,Robert,Sales Representative,Mr.,1992-05-29,2026-01-02,Edgeham Hollow Winchester Way,London,British Isles,RG1 9SP,UK,(71) 555-5598,465,None,Robert King served in the Peace Corps and trav...,5.0,http://accweb/emmployees/davolio.bmp
7,8,Callahan,Laura,Inside Sales Coordinator,Ms.,1990-01-09,2026-03-05,4726 - 11th Ave. N.E.,Seattle,North America,98105,USA,(206) 555-1189,2344,None,Laura received a BA in psychology from the Uni...,2.0,http://accweb/emmployees/davolio.bmp
8,9,Dodsworth,Anne,Sales Representative,Ms.,1998-01-27,2026-11-15,7 Houndstooth Rd.,London,British Isles,WG2 7LT,UK,(71) 555-4444,452,None,Anne has a BA degree in English from St. Lawre...,5.0,http://accweb/emmployees/davolio.bmp

In [163]:
nw = Northwind("Northwind_small.sqlite")

In [164]:
nw.list_table_names()

['Employee',
 'Category',
 'Customer',
 'Shipper',
 'Supplier',
 'Order',
 'Product',
 'OrderDetail',
 'CustomerCustomerDemo',
 'CustomerDemographic',
 'Region',
 'Territory',
 'EmployeeTerritory']

### Assessment